var GAME_LEVELS = [
  ["                                                                                ",
   "                                  xxxxx  xxxxx                                  ",
   "                        yy        x!!!x  x!!!x                                  ",
   "                       yyy        x!!!x  x!!!x                                  ",
   "            yyyyy                 xx!xx  xx!xx              yy   yyyy           ",
   "           yyyyyyy                 xvx    xvx                  yyyyy            ",
   "              yyyyy                                                             ",
   "                                        o                                       ",
   "                                                                                ",
   "                                        o                                       ",
   "                           o     xxxxxxxxxxxxxxx                o               ",
   "                                                   xx         o   o         xx  ",
   "  xx                      xxx                                 x x x          x  ",
   "  x           oo   xxxx                                       xxxxx          x  ",
   "  x                x  x           oo                          x x x          x  ",
   "  x          xxxx  x  x                                    x xxxxxxx x       x  ",
   "  x  @      xx  x!!x  x          xxxx           o          xxxxxxxxxxx    o  x  ",
   "  xxxxxxxxxxx   xxxx  xxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                          x    xxx    x                         ",
   "                                          x           x                         ",
   "                                          x!!!!!!!!!!!x                         ",
   "                                          xx!!!!!!!!!xx                         ",
   "                                           xxxxxxxxxxx                          ",
   "                                                                                "],
  ["                                                                                                              ",
   "                                                                                            xxxxx             ",
   "                                 xxxxxx                                   xxxxxx            x!!!x             ",
   "    yyyyyy                                         yyyy                                     x!!!x      yyyyy  ",
   "      yyyyyy        yyyy                          yyyy                                      xx!xx     yyy     ",
   "  yyyyyyy          yyy                             yyyyyy                                    xvx              ",
   "                                 xxxxx      x                              xxxxxx                             ",
   "                            xx        x~~~~~x~~~~~~~~~~~~~~~~~~~~~~~~~~~~~x                                   ",
   "                                      x~~~~~x~~~~~~~~~~~~~~~~~~~~~~~~xxx~~x                                   ",
   "                                      x~~~~~x~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~x             oo                   ",
   "                                     x~~~~~~x~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~x                                 ",
   "                          xxxx      x~~~~~~x~~~~~~~~ ~~~~~~~~~~xxx~~~~~~~~~~~x          xxxx                  ",
   "                                   x~~~~~~x~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~>~~~x                               ",
   "                     xxx          x~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~>~~~~~~~x                    x         ",
   "   @              xxxx           x~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~o~~~~~~~~x                   x         ",
   " xxxxx           ox             x~~~~~o~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~x~~~~~~~~~x                  x         ",
   "     x           xx            x~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~o~~~~~~~~~~~~~~x              xxxx         ",
   "     xx           x           x~~~~~~xxx~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~x                          ",
   "      xx          x           x~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~o~~~x~~~~~~~~~~~~~~~x                          ",
   "       xxxxxxxxxxxx           x~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~x                          ",
   "                              x~~~~~~~~~~~~~~~~~~~~~~xxxx~~~~~~x~~~~~~~~~~~~~~~~~~~x    xxx                  x",
   "                              x~~~~~~~~~~~~>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~x                         x",
   "                              x~~~~~~~~~~~~~~>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~x                     o   x",
   "                              x~~~~~~~~~~~~>~~~o~~~~~~~~~~~~~~~~~~~~~~~~o~~~~~~~~~~x                   o   o x",
   "                               x~~~~~~~~~~~~~~xxx~~~~~~~~~~~~~~~~~~~o~~xxx~~o~~~~~x                          x",
   "                                x~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~>x~xx~xx~x~~~~x                 xxxxxxxxxxx",
   "                                 xxx~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~xxxxxxxxx~xxx                             ",
   "                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                       xxxxx                                                  ",
   "                                                       x   x                                                  ",
   "       yyyyyy                                  xxxxx   x   x   xxxxx                 yyyyyyy                  ",
   "         yyyyy    yyyyy                        x   x   x   x   x   x                   yyyyy                  ",
   "     yyyyyyyyy      yyyy                       x   x   x   x   x   x                               yy         ",
   "                                               x   x  x     x  x   x                            yyyyy         ",
   "                              xxx xxx xxx      x   xxxx     xxxx   x      xxx xxx xxx           yy            ",
   "                              x x x x x x      x                   x      x x x x x x                         ",
   "x                             x x x x x x      xb o  o b   b o  o bx      x x x x x x                         ",
   "x                             x xxx xxx x      xxxxxxxxxbbbxxxxxxxxx      x xxx xxx x                         ",
   "x                             x         x      x                   x      x         x                         ",
   "x  @                           x       x       x=                  x       x       x                          ",
   "xxxxxx                          xo   ox        x        b          x        xo   ox                           ",
   "     x                           xbbbx         x       xx         =x         xbbbx                            ",
   "     x                           xbbbx         x              b    x         xbbbx                            ",
   "     x                           x  xxxxxxxxxxxx       bb    xxx   xxxxxxxxxxxx  x                            ",
   "     xxxxx                       x     x!!!!!x         bb                        x                            ",
   "         x                       xo       v                                     ox                            ",
   "         x                       xb                 xxxxx                       bx                            ",
   "         x                       xx                                             xx                            ",
   "         x                       x  bb        bbbb          bbbb                 x                            ",
   "         xxx                     x  bb        xxxx          xxxxx                x                            ",
   "           x      x              xb      b    x!!x          xxxxxx        b     bx                            ",
   "           x      xxxxxxxxxxxxxxxxx      xxxxxx vx        bbxxxxxxxb     xxx    xxxxxxxxxxxxxxxxxxxxx         ",
   "           x             ^       x      x        x        xxxxxxxxxxb                 b   b         x         ",
   "           x                      bbb  x         x          xxxxxxxxx                 b   b         x         ",
   "           x          o          pbbb x  o                  xxxxxxxxxx       o o o    b   bn        x         ",
   "           x                     xbbbx  o o   bbbbbbbbb     xxxxxxxxxxx               b   b         x         ",
   "           xxxxxxx ^ xxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxx         ",
   "                 x!!!!!!!!!x                                                               x   x              ",
   "                 x!!!!!!!!!x                                                               x~~~x              ",
   "                 xxxxxxxxxxx                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx~~~x              ",
   "                                                        x~~ ~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~ ~~~~~x              ",
   "                                                        x~~~~~~~<~<~~~ ~~~ ~~~~~<~~~<<~<~~~~~~~x              ",
   "                                                        x~~~~<<oo~<~~~~~~~~~~~ ~~~~~~~~~~~~~~ ~x              ",
   "                                                        x~~~~<x~~x~<~~~xxxxxxxxxxxxxxxxxxxxxxxxx              ",
   "                                                        x~~x~xxxxxx~x~~x                                      ",
   "                                                        x~~xxx~xx~xxx~~x                                      ",
   "                                                        xxxxxxxxxxxxxxxx                                      ",
   "                                                                                                              ",
   "                                                                                                         "],
  ["                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "               y       y   yyy    y     y       y             y             y  y  y      y  y            ",
   "                y     y   y   y   y     y        y           y y           y   y  yy     y  y            ",
   "                 y   y   y     y  y     y         y         y   y         y    y  y y    y  y            ",
   "                  y y    y     y  y     y          y       y     y       y     y  y  y   y  y            ",
   "                   y     y     y  y     y           y     y       y     y      y  y   y  y  y            ",
   "                   y     y     y  y     y            y   y         y   y       y  y    y y  y            ",
   "                   y      y   y    y   y              y y           y y        y  y     yy               ",
   "                   y       yyy      yyy                y             y         y  y      y  y            ",
   "       @                                                                                                 ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                         ",
   "                                                                                                         "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
